name: E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  e2e:
    name: E2E Testing 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: |
          yarn install
          cd test
          yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./test
          browser: chrome
          start: yarn --cwd ../ dev
          command: npx cypress run
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 300
